theme: minima
title: Fangming Xie's homepage

author:
  name: Fangming Xie
  email: f7xie@ucsd.edu
description:  

# this restricts header page to the following only (ordered)
header_pages:  
# - research.md
# - publications.md
# - teaching.md 
- CV.md 

# where these go?
minima:
  social_links:
      github: fangmingxie
    # twitter:
    # google scholar:

google_analytics: UA-NNNNNNNN-N
github: [metadata]
