# theme: jekyll-theme-minimal
theme: minima


author:
  name: Fangming Xie
  email: "f7xie@ucsd.edu"

header_pages: 
- research.md
- publications.md
- teaching.md 
- CV.md # a link to CV pdf
- about.md # personal

minima:
  social_links:
    twitter: jekyllrb
    github: jekyll

