# theme: jekyll-theme-minimal
title: Fangming Xie
theme: minima

author:
  name: Fangming Xie
  email: f7xie@ucsd.edu
  description: >
    ...

# header_pages: 
- research.md
- publications.md
- teaching.md 
- CV.md # a link to CV pdf
- about.md # personal

minima:
  social_links:
      github: fangmingxie
    # twitter:
    # google scholar:


